import Foundation
import SwiftData

enum ExerciseActivityType: String, CaseIterable, Identifiable, Codable, Sendable {
    case basketball
    case running

    var id: String { rawValue }

    var label: String {
        switch self {
        case .basketball: return "篮球"
        case .running: return "跑步"
        }
    }

    var systemImage: String {
        switch self {
        case .basketball: return "basketball"
        case .running: return "figure.run"
        }
    }
}

/// 运动强度快照所对应的 2024 Adult Compendium 条目。
///
/// MET 与 Compendium code 会在保存时复制进 `ExerciseEntry`，以后即使预设更新，
/// 历史记录仍能按当时采用的算法复核。
enum ExerciseIntensity: String, CaseIterable, Identifiable, Codable, Sendable {
    case basketballShooting
    case basketballGeneral
    case basketballGame
    case runningSlow
    case runningModerate
    case runningFast

    var id: String { rawValue }

    var activityType: ExerciseActivityType {
        switch self {
        case .basketballShooting, .basketballGeneral, .basketballGame:
            return .basketball
        case .runningSlow, .runningModerate, .runningFast:
            return .running
        }
    }

    var label: String {
        switch self {
        case .basketballShooting: return "投篮练习"
        case .basketballGeneral: return "一般强度"
        case .basketballGame: return "比赛强度"
        case .runningSlow: return "慢跑"
        case .runningModerate: return "中速跑"
        case .runningFast: return "快速跑"
        }
    }

    var detail: String {
        switch self {
        case .basketballShooting: return "投篮、罚球等练习"
        case .basketballGeneral: return "一般球局，包含走动和短暂停顿"
        case .basketballGame: return "持续对抗或全场比赛"
        case .runningSlow: return "约 4.0–4.2 mph（约 13 分/英里）"
        case .runningModerate: return "约 5.0–5.2 mph（约 12 分/英里）"
        case .runningFast: return "约 7.0 mph（约 8.5 分/英里）"
        }
    }

    var metValue: Double {
        switch self {
        case .basketballShooting: return 5.0
        case .basketballGeneral: return 6.0
        case .basketballGame: return 8.0
        case .runningSlow: return 6.5
        case .runningModerate: return 8.5
        case .runningFast: return 11.0
        }
    }

    var compendiumCode: String {
        switch self {
        case .basketballShooting: return "15070"
        case .basketballGeneral: return "15050"
        case .basketballGame: return "15040"
        case .runningSlow: return "12028"
        case .runningModerate: return "12030"
        case .runningFast: return "12070"
        }
    }

    static func presets(for activityType: ExerciseActivityType) -> [ExerciseIntensity] {
        allCases.filter { $0.activityType == activityType }
    }

    static func defaultIntensity(for activityType: ExerciseActivityType) -> ExerciseIntensity {
        switch activityType {
        case .basketball: return .basketballGeneral
        case .running: return .runningModerate
        }
    }
}

@Model
final class ExerciseEntry {
    var startDate: Date
    var durationMinutes: Double
    var activityTypeRaw: String
    var intensityRaw: String
    var name: String
    var compendiumCode: String
    var metSnapshot: Double
    var weightKgSnapshot: Double
    var estimatedActiveEnergyKcal: Double
    var calculationVersion: Int

    init(
        startDate: Date = .now,
        durationMinutes: Double,
        activityType: ExerciseActivityType,
        intensity: ExerciseIntensity,
        name: String? = nil,
        compendiumCode: String,
        metSnapshot: Double,
        weightKgSnapshot: Double,
        estimatedActiveEnergyKcal: Double,
        calculationVersion: Int = ExerciseEnergyEngine.calculationVersion
    ) {
        self.startDate = startDate
        self.durationMinutes = durationMinutes
        self.activityTypeRaw = activityType.rawValue
        self.intensityRaw = intensity.rawValue
        self.name = name ?? "\(activityType.label) · \(intensity.label)"
        self.compendiumCode = compendiumCode
        self.metSnapshot = metSnapshot
        self.weightKgSnapshot = weightKgSnapshot
        self.estimatedActiveEnergyKcal = estimatedActiveEnergyKcal
        self.calculationVersion = calculationVersion
    }

    var activityType: ExerciseActivityType? {
        ExerciseActivityType(rawValue: activityTypeRaw)
    }

    var intensity: ExerciseIntensity? {
        ExerciseIntensity(rawValue: intensityRaw)
    }

    /// Returns a localized title for names generated by the app while leaving
    /// user-provided names byte-for-byte unchanged.
    ///
    /// Older records persist the Simplified Chinese generated title in `name`.
    /// Comparing it with the activity/intensity snapshot lets the display layer
    /// localize those records without changing the SwiftData schema or history.
    func displayName(locale: Locale) -> String {
        guard
            let activityType,
            let intensity,
            name == "\(activityType.label) · \(intensity.label)"
        else {
            return name
        }

        let activityLabel = interfaceLocalized(activityType.label, locale: locale)
        let intensityLabel = interfaceLocalized(intensity.label, locale: locale)
        return "\(activityLabel) · \(intensityLabel)"
    }

    var endDate: Date {
        guard durationMinutes.isFinite, durationMinutes > 0 else { return startDate }
        let endDate = startDate.addingTimeInterval(durationMinutes * 60)
        return endDate.timeIntervalSinceReferenceDate.isFinite ? endDate : startDate
    }

    var energyInterval: ExerciseEnergyInterval {
        ExerciseEnergyInterval(
            startDate: startDate,
            endDate: endDate,
            estimatedActiveEnergyKcal: estimatedActiveEnergyKcal
        )
    }

    static func estimated(
        startDate: Date = .now,
        durationMinutes: Double,
        intensity: ExerciseIntensity,
        weightKg: Double,
        name: String? = nil
    ) -> ExerciseEntry? {
        guard let energy = ExerciseEnergyEngine.estimateActiveEnergyKcal(
            intensity: intensity,
            weightKg: weightKg,
            durationMinutes: durationMinutes
        ) else {
            return nil
        }

        return ExerciseEntry(
            startDate: startDate,
            durationMinutes: durationMinutes,
            activityType: intensity.activityType,
            intensity: intensity,
            name: name,
            compendiumCode: intensity.compendiumCode,
            metSnapshot: intensity.metValue,
            weightKgSnapshot: weightKg,
            estimatedActiveEnergyKcal: energy
        )
    }
}
